name: Build React on S3
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Checkout
        uses: actions/checkout@v2  # リポジトリをチェックアウト
        with:
          ref: main

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build  # React ビルド

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: s3:/kohki-ohno-developer-github-sync
        run: # S3のbucket-for-deploying-react-projectバケットにデプロイ 
          aws s3 cp --recursive --region ap-northeast-1 build ${AWS_BUCKET}
          
